<?php
/**
 * @file
 * Code for the GSB Feature Event Shared feature.
 */

include_once 'gsb_feature_event_shared.features.inc';

/**
 * Implements hook_node_view().
 */
function gsb_feature_event_shared_node_view_alter(&$build) {
  if ($build['#node']->type == 'event' || $build['#node']->type == 'admission_event') {
    if (count($build['field_event_speakers']['#items']) <= 1) {
      $speaker_entity_id = $build['field_event_speakers']['#items'][0]['value'];
      $speaker_entity = $build['field_event_speakers'][0]['entity']['field_collection_item'][$speaker_entity_id];
      if (empty($speaker_entity['#entity']->field_person_ref) && empty($speaker_entity['#entity']->field_first_name)
          && empty($speaker_entity['#entity']->field_last_name)) {
        $build['field_event_speakers']['#access'] = FALSE;
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gsb_feature_event_shared_form_node_form_alter(&$form, &$form_state) {
  if ($form['#bundle'] == 'event' || $form['#bundle']  == 'admission_event') {
    foreach($form['field_event_location']['und'] as $key) {
      if (is_numeric($key) && $key >= 0) {
        // Make street address and zip code NOT required
        $form['field_event_location']['und'][$key]['field_address']['und'][0]['street_block']['thoroughfare']['#required'] = FALSE;
        $form['field_event_location']['und'][$key]['field_address']['und'][0]['locality_block']['postal_code']['#required'] = FALSE;
      }
    }
  }
}
